- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 # One day
    
- name: Install pip3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
  
- pip:
    name: docker

- name: Start nodeexporter container
  docker_container:
    name: nodeexporter
    image: quay.io/prometheus/node-exporter:v1.0.1
    restart_policy: always
    network_mode: "host"
    pid_mode: "host"
    hostname: "{{ ansible_hostname }}"
    volumes:
      - "/:/host:ro,rslave"
    # ports:
    #   - 9100:9100
    command: ["--path.rootfs=/host"]
