---
- name: Setup Center servers
  hosts: center
  become: yes

  roles:
    - { 
      role: prometheus-center,
    }
  
# - name: Setup Exporter servers
#   hosts: exporter
#   become: yes

#   roles:
#     - { 
#       role: prometheus-exporter,
#     }
  