---
- name: Setup Center servers
  hosts: center
  become: yes

  roles:
    - { 
      role: prometheus-center,
      node_exporter_targets: ["10.0.0.3:9100", "10.0.0.4:9100"],
      cadvisor_targets: ["10.0.0.3:9200", "10.0.0.4:9200"],
    }
  
- name: Setup Exporter servers
  hosts: exporter
  become: yes
  roles:
    - { 
      role: prometheus-exporter,
    }
  