---
- name: Setup Center servers
  hosts: center
  become: yes

  roles:
    - { 
      role: prometheus-center,
    }
  
- name: Setup Node Exporter
  hosts: node-exporter
  become: yes
  roles:
    - { 
      role: node-exporter,
    }

- name: Setup Container Exporter
  hosts: container-exporter
  become: yes
  roles:
    - { 
      role: node-exporter,
    }

- name: Setup Nginx Exporter
  hosts: nginx-exporter
  become: yes
  roles:
    - { 
      role: nginx-exporter,
    }
  