---
- name: Setup Center servers
  hosts: center
  become: yes

  roles:
    - { 
      role: prometheus-center,
    }
  
- name: Setup Exporter servers
  hosts: exporter
  become: yes
  roles:
    - { 
      role: prometheus-exporter,
    }

- name: Setup Nginx exporter servers
  hosts: nginx
  become: yes
  roles:
    - { 
      role: nginx-exporter,
    }
  