- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 # One day
    
- name: Install pip3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
  
- pip:
    name: docker

- name: Start nginxexporter container
  docker_container:
    name: nginxexporter
    image: nginx/nginx-prometheus-exporter:0.8.0
    restart_policy: always
    networks:
      - name: "traefik-net"
    hostname: "{{ ansible_hostname }}"
    ports:
      - "{{ hostvars[inventory_hostname].internal_ip }}9113:9113"
    command: ["-nginx.scrape-uri", "http://nginx:9300/status"]
